---
title: "Um bom exemplo de análise"
author: "Luiz Alberto Fonseca"
date: "23 de maio de 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

O site [League of Graphs](http://www.leagueofgraphs.com/pt/) traz análises sobre os dados do famoso jogo online League of Legends.
Os dados incluem quais os personagens (campeões, no linguajar do jogo) mais jogados, quais deles têm a maior porcentagem de partidas ganhas, quais os campeões mais banidos das partidas (cada time pode banir até 3 campeões por parida) e outras informações relacionadas aos campeões, partidas e jogadores.

Para cada personagem você pode visualizar a popularidade (A porcentagem de patidas em que aquele campeão aparece), a porcentagem de vitórias, a taxa de banimento, o KDA (a média de abatimentos, mortes e assistências em abatimentos), a razão de penta kills (quando um campeão mata todos os outros da equipe inimiga) por jogo e a progressão de popularidade do campeão desde o lançamento da última atualização.

O site utiliza diversos meios gráficos: gráficos de barra, infográficos, gráficos de aro, gráficos de área, entre outros. A medida estatística mais utilizada é a média e também é bastante utilizada a porcentagem para descrever os dados por campeão ou por partida, por exemplo.

Eu acredito que esta é uma análise bem feita pois explora os mesmos dados de formas diferentes, com visualizações interessantes que,  embora um pouco repetitivas, são fáceis de ler e de entender. Acho que algo que eu teria feito diferente seria desagregar mais as visualizações. Podemos ver que há uma tabela onde cada campeão é uma linha e cada coluna é um tipo de visualização dos dados. Eu teria separado cada coluna da tabela em uma visualização independente e com isso poderia diversificar a forma como os dados são apresentados.